"""Computational text-analysis utilities for the Stevenson research corpus."""

from .agreement import agreement_summary, cohens_kappa, compare_annotation_sets, observed_agreement
from .analysis import concordance, count_terms, lexical_summary, segment_term_counts, significant_collocates
from .annotations import (
    ALLOWED_CATEGORIES,
    ALLOWED_CLAIM_ROLES,
    ResearchAnnotation,
    annotation_summary,
    load_annotations_csv,
    resolve_annotation_anchors,
    validate_annotations,
)
from .comparison import (
    CorpusText,
    leave_one_out_reference_rates,
    pool_tokens,
    research_term_comparison,
    target_vs_pooled_reference,
    term_rate_matrix,
)
from .corpus import TextDocument, fetch_document, normalize_text, tokenize
from .morphology import (
    lemma_concordance,
    lemma_counts,
    lemma_lookup,
    lemmatize_tokens,
    validate_lemma_groups,
)
from .networks import cooccurrence_network
from .phrases import frequent_ngrams, frequent_skipgrams, ngrams, phrase_counts, phrase_occurrences, skipgrams
from .statistics import dispersion_profile, log_likelihood_keyness
from .structure import TextSection, count_alias_groups, section_entity_matrix, split_by_headings
from .tei import (
    TEICorrespondence,
    TEIDocumentObject,
    TEIRelation,
    TEISection,
    correspondence_edges,
    document_circulation_edges,
    entity_frequencies,
    extract_correspondence,
    extract_document_objects,
    extract_named_entities,
    extract_relations,
    extract_tei_sections,
    parse_tei,
    query_elements,
    relation_edges,
    sections_containing_ref,
    tei_title,
)

__all__ = [
    "ALLOWED_CATEGORIES",
    "ALLOWED_CLAIM_ROLES",
    "CorpusText",
    "ResearchAnnotation",
    "TEICorrespondence",
    "TEIDocumentObject",
    "TEIRelation",
    "TEISection",
    "TextDocument",
    "TextSection",
    "agreement_summary",
    "annotation_summary",
    "cohens_kappa",
    "compare_annotation_sets",
    "concordance",
    "cooccurrence_network",
    "correspondence_edges",
    "count_alias_groups",
    "count_terms",
    "dispersion_profile",
    "document_circulation_edges",
    "entity_frequencies",
    "extract_correspondence",
    "extract_document_objects",
    "extract_named_entities",
    "extract_relations",
    "extract_tei_sections",
    "fetch_document",
    "frequent_ngrams",
    "frequent_skipgrams",
    "leave_one_out_reference_rates",
    "lemma_concordance",
    "lemma_counts",
    "lemma_lookup",
    "lemmatize_tokens",
    "lexical_summary",
    "load_annotations_csv",
    "log_likelihood_keyness",
    "ngrams",
    "normalize_text",
    "observed_agreement",
    "parse_tei",
    "phrase_counts",
    "phrase_occurrences",
    "pool_tokens",
    "query_elements",
    "relation_edges",
    "research_term_comparison",
    "resolve_annotation_anchors",
    "section_entity_matrix",
    "sections_containing_ref",
    "segment_term_counts",
    "significant_collocates",
    "skipgrams",
    "split_by_headings",
    "target_vs_pooled_reference",
    "tei_title",
    "term_rate_matrix",
    "tokenize",
    "validate_annotations",
    "validate_lemma_groups",
]
