const datasetSelect = document.querySelector("#dataset");
const filterInput = document.querySelector("#filter");
const table = document.querySelector("#results");
const status = document.querySelector("#status");
const network = document.querySelector("#network");
const networkStatus = document.querySelector("#network-status");
const networkList = document.querySelector("#network-list");
const reloadNetwork = document.querySelector("#reload-network");
const reloadScenes = document.querySelector("#reload-scenes");
const sceneStatus = document.querySelector("#scene-status");
const sceneCards = document.querySelector("#scene-cards");

let rows = [];
let targetEbookId = null;

function parseCSV(text) {
  const result = [];
  let row = [];
  let cell = "";
  let quoted = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (char === '"' && quoted && next === '"') {
      cell += '"';
      i += 1;
    } else if (char === '"') {
      quoted = !quoted;
    } else if (char === "," && !quoted) {
      row.push(cell);
      cell = "";
    } else if ((char === "\n" || char === "\r") && !quoted) {
      if (char === "\r" && next === "\n") i += 1;
      row.push(cell);
      if (row.some(value => value !== "")) result.push(row);
      row = [];
      cell = "";
    } else {
      cell += char;
    }
  }

  if (cell || row.length) {
    row.push(cell);
    result.push(row);
  }
  return result;
}

function records(data) {
  if (!data.length) return [];
  const [header, ...body] = data;
  return body.map(values => Object.fromEntries(header.map((key, index) => [key, values[index] ?? ""])));
}

async function loadTargetMetadata() {
  const response = await fetch("../data/source_manifest.csv");
  if (!response.ok) throw new Error(`Source manifest unavailable: HTTP ${response.status}`);

  const manifestRows = records(parseCSV(await response.text()));
  const targets = manifestRows.filter(row => row.corpus_role === "target");
  if (targets.length !== 1 || !targets[0].ebook_id) {
    throw new Error("Source manifest must declare exactly one target with an ebook_id.");
  }

  targetEbookId = targets[0].ebook_id;
  Array.from(datasetSelect.options).forEach(option => {
    if (option.value.includes("{target}")) {
      option.value = option.value.replace("{target}", targetEbookId);
    }
  });
}

function render(data) {
  table.replaceChildren();
  if (!data.length) {
    status.textContent = "No matching rows.";
    return;
  }

  const [header, ...body] = data;
  const thead = document.createElement("thead");
  const tr = document.createElement("tr");
  header.forEach(value => {
    const th = document.createElement("th");
    th.scope = "col";
    th.textContent = value;
    tr.append(th);
  });
  thead.append(tr);

  const tbody = document.createElement("tbody");
  body.forEach(values => {
    const bodyRow = document.createElement("tr");
    header.forEach((_, index) => {
      const td = document.createElement("td");
      td.textContent = values[index] ?? "";
      bodyRow.append(td);
    });
    tbody.append(bodyRow);
  });

  table.append(thead, tbody);
  status.textContent = `${body.length.toLocaleString()} row${body.length === 1 ? "" : "s"} shown.`;
}

function applyFilter() {
  const query = filterInput.value.trim().toLowerCase();
  if (!query) {
    render(rows);
    return;
  }
  const [header, ...body] = rows;
  render([header, ...body.filter(row => row.some(cell => cell.toLowerCase().includes(query)))]);
}

async function loadDataset() {
  status.textContent = "Loading…";
  table.replaceChildren();
  try {
    const response = await fetch(datasetSelect.value);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    rows = parseCSV(await response.text());
    applyFilter();
  } catch (error) {
    rows = [];
    status.textContent = "This dataset is generated by the Python pipeline and is not available in the current static preview.";
  }
}

function svgElement(name, attributes = {}) {
  const element = document.createElementNS("http://www.w3.org/2000/svg", name);
  Object.entries(attributes).forEach(([key, value]) => element.setAttribute(key, value));
  return element;
}

function renderNetwork(nodeRows, edgeRows) {
  const title = network.querySelector("title");
  const desc = network.querySelector("desc");
  network.replaceChildren(title, desc);

  const width = 800;
  const height = 520;
  const centerX = width / 2;
  const centerY = height / 2 - 10;
  const radius = Math.min(width, height) * .33;

  const positioned = nodeRows.map((node, index) => {
    const angle = (Math.PI * 2 * index / Math.max(nodeRows.length, 1)) - Math.PI / 2;
    return {
      ...node,
      x: centerX + radius * Math.cos(angle),
      y: centerY + radius * Math.sin(angle),
    };
  });
  const byId = new Map(positioned.map(node => [node.id, node]));

  edgeRows.forEach(edge => {
    const source = byId.get(edge.source);
    const target = byId.get(edge.target);
    if (!source || !target) return;
    const weight = Number(edge.weight) || 1;
    network.append(svgElement("line", {
      x1: source.x, y1: source.y, x2: target.x, y2: target.y,
      class: "network-edge",
      "stroke-width": Math.min(2 + weight * 1.5, 12),
    }));
  });

  positioned.forEach(node => {
    const group = svgElement("g");
    const sections = Number(node.sections_present) || 1;
    const nodeRadius = Math.min(15 + sections * 2, 34);
    group.append(svgElement("circle", {
      cx: node.x, cy: node.y, r: nodeRadius, class: "network-node",
    }));
    const label = svgElement("text", {
      x: node.x, y: node.y + nodeRadius + 7, class: "network-label",
    });
    label.textContent = node.id;
    group.append(label);
    const tooltip = svgElement("title");
    tooltip.textContent = `${node.id}: present in ${sections} section${sections === 1 ? "" : "s"}`;
    group.append(tooltip);
    network.append(group);
  });

  const list = document.createElement("ul");
  edgeRows.forEach(edge => {
    const item = document.createElement("li");
    item.textContent = `${edge.source} — ${edge.target}: ${edge.weight} shared section${edge.weight === "1" ? "" : "s"}`;
    list.append(item);
  });
  networkList.replaceChildren(list);
  networkStatus.textContent = `${nodeRows.length} characters and ${edgeRows.length} weighted relationships shown.`;
}

async function loadNetwork() {
  networkStatus.textContent = "Loading network…";
  try {
    if (!targetEbookId) throw new Error("Target corpus metadata unavailable");
    const [nodesResponse, edgesResponse] = await Promise.all([
      fetch(`../outputs/${targetEbookId}_network_nodes.csv`),
      fetch(`../outputs/${targetEbookId}_network_edges.csv`),
    ]);
    if (!nodesResponse.ok || !edgesResponse.ok) throw new Error("Network outputs unavailable");
    const nodeRows = records(parseCSV(await nodesResponse.text()));
    const edgeRows = records(parseCSV(await edgesResponse.text()));
    renderNetwork(nodeRows, edgeRows);
  } catch (error) {
    networkStatus.textContent = "Run the Python pipeline first to generate the network data.";
    networkList.replaceChildren();
  }
}

datasetSelect.addEventListener("change", loadDataset);
filterInput.addEventListener("input", applyFilter);
reloadNetwork.addEventListener("click", loadNetwork);


function renderScenes(sceneRows, bundleRows = []) {
  sceneCards.replaceChildren();
  sceneRows.forEach(scene => {
    const article = document.createElement("article");
    article.className = "scene-card";

    const meta = document.createElement("p");
    meta.className = "scene-meta";
    meta.textContent = `${scene.scene_id} · ${scene.section} · ${scene.scene_type}`;

    const heading = document.createElement("h3");
    heading.textContent = scene.title;

    const text = document.createElement("p");
    text.textContent = scene.window_text || "No resolved scene window.";

    const rationale = document.createElement("p");
    rationale.className = "scene-rationale";
    rationale.textContent = scene.rationale;

    const state = document.createElement("p");
    state.className = "scene-state";
    state.textContent = `Anchor: “${scene.anchor_phrase}” · ${scene.status}`;

    const related = bundleRows.filter(bundle => bundle.scene_id === scene.scene_id);
    if (related.length) {
      const evidenceHeading = document.createElement("h4");
      evidenceHeading.textContent = "Linked evidence";
      const evidenceList = document.createElement("ul");
      evidenceList.className = "evidence-list";

      related.forEach(bundle => {
        const item = document.createElement("li");
        const parts = [];
        if (bundle.annotation_id) {
          parts.push(`${bundle.annotation_id}: ${bundle.annotation_category} (${bundle.annotation_claim_role})`);
        }
        if (bundle.document_ref) parts.push(`document ${bundle.document_ref}`);
        if (bundle.relation) parts.push(`relation: ${bundle.relation}`);
        item.textContent = parts.join(" · ");
        if (bundle.annotation_note) {
          const note = document.createElement("span");
          note.className = "evidence-note";
          note.textContent = ` — ${bundle.annotation_note}`;
          item.append(note);
        }
        evidenceList.append(item);
      });
      article.append(evidenceHeading, evidenceList);
    }

    article.append(meta, heading, text, rationale, state);
    sceneCards.append(article);
  });
  sceneStatus.textContent = `${sceneRows.length} research scene${sceneRows.length === 1 ? "" : "s"} shown.`;
}

async function loadScenes() {
  sceneStatus.textContent = "Loading research scenes…";
  try {
    const [sceneResponse, bundleResponse] = await Promise.all([
      fetch("../outputs/research_scenes.csv"),
      fetch("../outputs/evidence_bundles.csv"),
    ]);
    if (!sceneResponse.ok) throw new Error("Scene output unavailable");
    const sceneRows = records(parseCSV(await sceneResponse.text()));
    const bundleRows = bundleResponse.ok ? records(parseCSV(await bundleResponse.text())) : [];
    renderScenes(sceneRows, bundleRows);
  } catch (error) {
    sceneCards.replaceChildren();
    sceneStatus.textContent = "Run the Python pipeline first to generate research-scene windows.";
  }
}

reloadScenes.addEventListener("click", loadScenes);

async function initialize() {
  try {
    await loadTargetMetadata();
  } catch (error) {
    networkStatus.textContent = "Could not read target corpus metadata.";
  }
  await Promise.all([loadDataset(), loadNetwork(), loadScenes()]);
}

initialize();
