const datasetSelect = document.querySelector("#dataset");
const filterInput = document.querySelector("#filter");
const table = document.querySelector("#results");
const status = document.querySelector("#status");

let rows = [];

function parseCSV(text) {
  const result = [];
  let row = [];
  let cell = "";
  let quoted = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (char === '"' && quoted && next === '"') {
      cell += '"';
      i += 1;
    } else if (char === '"') {
      quoted = !quoted;
    } else if (char === "," && !quoted) {
      row.push(cell);
      cell = "";
    } else if ((char === "\n" || char === "\r") && !quoted) {
      if (char === "\r" && next === "\n") i += 1;
      row.push(cell);
      if (row.some(value => value !== "")) result.push(row);
      row = [];
      cell = "";
    } else {
      cell += char;
    }
  }

  if (cell || row.length) {
    row.push(cell);
    result.push(row);
  }
  return result;
}

function render(data) {
  table.replaceChildren();
  if (!data.length) {
    status.textContent = "No matching rows.";
    return;
  }

  const [header, ...body] = data;
  const thead = document.createElement("thead");
  const tr = document.createElement("tr");
  header.forEach(value => {
    const th = document.createElement("th");
    th.scope = "col";
    th.textContent = value;
    tr.append(th);
  });
  thead.append(tr);

  const tbody = document.createElement("tbody");
  body.forEach(values => {
    const bodyRow = document.createElement("tr");
    header.forEach((_, index) => {
      const td = document.createElement("td");
      td.textContent = values[index] ?? "";
      bodyRow.append(td);
    });
    tbody.append(bodyRow);
  });

  table.append(thead, tbody);
  status.textContent = `${body.length.toLocaleString()} row${body.length === 1 ? "" : "s"} shown.`;
}

function applyFilter() {
  const query = filterInput.value.trim().toLowerCase();
  if (!query) {
    render(rows);
    return;
  }
  const [header, ...body] = rows;
  render([header, ...body.filter(row => row.some(cell => cell.toLowerCase().includes(query)))]);
}

async function loadDataset() {
  status.textContent = "Loading…";
  table.replaceChildren();
  try {
    const response = await fetch(datasetSelect.value);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    rows = parseCSV(await response.text());
    applyFilter();
  } catch (error) {
    rows = [];
    status.textContent = "This dataset is generated by the Python pipeline and is not available in the current static preview.";
  }
}

datasetSelect.addEventListener("change", loadDataset);
filterInput.addEventListener("input", applyFilter);
loadDataset();
